CREATE DATABASE projekt_sklep3
GO
use projekt_sklep3
GO
CREATE TABLE kategoria (
ID INT NOT NULL IDENTITY PRIMARY KEY,
nazwa VARCHAR(100) NOT NULL,
zdjecie VARCHAR(100) NULL,
ilosc VARCHAR(100) NOT NULL,
 dostepnosc VARCHAR(100) NOT NULL
)
CREATE TABLE magazyn (
ID INT NOT NULL IDENTITY PRIMARY KEY,
nazwa VARCHAR(100) NOT NULL,
ilosc VARCHAR(100) NOT NULL,
data_przybycia DATETIME,
stan_produktu VARCHAR(100)
)
CREATE TABLE kraj_pochodzenia (
ID INT NOT NULL IDENTITY PRIMARY KEY,
nazwa VARCHAR(100) NOT NULL,
opis VARCHAR(100) NULL,
logotyp VARCHAR(100) NULL
)
CREATE TABLE produkt (
Produkt_ID INT NOT NULL IDENTITY PRIMARY KEY,
nazwa_produktu VARCHAR(100) NOT NULL,
opis VARCHAR(100) NULL,
model VARCHAR(100) NULL,
cena_produktu DECIMAL(8,2),
kat_ID INT FOREIGN KEY REFERENCES kategoria(ID),
magazyn_ID INT FOREIGN KEY REFERENCES magazyn(ID),
kraj_ID INT FOREIGN KEY REFERENCES kraj_pochodzenia(ID)
)
CREATE TABLE klient (
ID INT NOT NULL IDENTITY PRIMARY KEY,
imie VARCHAR(100) NOT NULL,
nazwisko VARCHAR(100) NOT NULL,
adres VARCHAR(100) NULL,
telefon VARCHAR(100) NULL,
e_mail VARCHAR(100) NULL,
IP_adress VARCHAR(100) NULL,
haslo VARCHAR(100) NULL,
zniszka VARCHAR(100) NULL
)
CREATE TABLE status_Z (
ID INT NOT NULL IDENTITY PRIMARY KEY,
nazwa VARCHAR(100) NOT NULL,
komentarz VARCHAR(100) NULL
)
CREATE TABLE zamowienie (
ID INT NOT NULL IDENTITY PRIMARY KEY,
nazwa_zamowienia VARCHAR(100) NOT NULL,
data_zamowienia DATETIME,
cena_produktu DECIMAL(8,2),
cena_zamowienia DECIMAL(8,2),
sposob_dostawy VARCHAR(100) NOT NULL,
sposob_oplaty VARCHAR(100) NOT NULL,
produkt_ID INT FOREIGN KEY REFERENCES produkt(Produkt_ID),
klient_ID INT FOREIGN KEY REFERENCES klient(ID),
status_ID INT FOREIGN KEY REFERENCES status_Z(ID)
);